export interface IAppUrls {
  INTERNAL_USER: string;
  TEAMS: string;
  CLAIM_BULK: string;
  TEAMS_INBOX: string;
  USER_INBOX: string;
  PERMISSIONS: string;
  BASE_URL: string;
  LOGIN_INFO: string;
  LANGUAGE: string;
  CUSTOM_ROLE: string;
  CUSTOM_ROLE_PERMISSIONS: string;
  LOOKUPS: string;
  ORGANIZATION_UNIT: string;
  ORGANIZATION_BRANCH: string;
  AID_LOOKUPS: string;
  AID_LOOKUPS_CRITERIA: string;
  ORGANIZATION: string;
  ORG_USER: string;
  CACHE_SERVICE: string;
  BENEFICIARY: string;
  SUBVENTION_REQUEST: string;
  SUBVENTION_REQUEST_PARTIAL: string;
  SUBVENTION_REQUEST_PARTIAL_LOG: string;
  SUBVENTION_REQUEST_AID: string;
  SUBVENTION_AID: string;
  SANADI_ATTACHMENT: string;
  ORG_USER_PERMISSION: string;
  AUTHENTICATE: string;
  VALIDATE_TOKEN: string;
  SUBVENTION_LOG: string;
  EXT_YOUTUBE: string;
  EXT_INSTAGRAM: string;
  EXT_FACEBOOK: string;
  EXT_TWITTER: string;
  EXT_RACA: string;
  INTERNAL_AUTHENTICATE: string;
  E_INQUIRY: string;
  E_CONSULTATION: string;
  E_INTERNATIONAL_COOPERATION: string;
  INTERNAL_DEPARTMENT: string;
  SERVICE_DATA:string;

  [index: string]: string;
}
