export interface IAppConfig {
  MAP_API_KEY: string;
  VERSION: string;
  TIMESTAMP: string;
  ENVIRONMENTS_URLS: Record<string, string>;
  BASE_ENVIRONMENT: string;
  BASE_URL: string;
  API_VERSION: string;
  TOKEN_HEADER_KEY: string;
  TOKEN_STORE_KEY: string;
  EXTERNAL_PROTOCOLS: string[];
  DEFAULT_DATE_FORMAT: string;
  DATEPICKER_FORMAT: string;
  SEARCH_YEARS_RANGE: number;
  SEARCH_YEARS_START: number;
  SEARCH_YEARS_BY: string;
  LANGUAGE_STORE_KEY: string;
  ADMIN_PERMISSIONS_GROUP: string[];
  MANAGE_ORG_PERMISSIONS_GROUP: string[];
  MANAGE_USER_PERMISSIONS_GROUP: string[];
  ALLOWED_FILE_TYPES_TO_UPLOAD: string[];
  GENERAL_SERVICES_PERMISSIONS_GROUP: string[];
  OFFICE_SERVICES_PERMISSIONS_GROUP: string[];
  PROJECTS_PERMISSION_GROUP: string[];
  SANADY_PERMISSIONS_GROUP: string[];
  TRAINING_PROGRAMS_PAGE_GROUP: string[];
  TRAINING_PROGRAMS_MENU_ITEM_GROUP: string[];
  COLLECTION_SERVICES_GROUP: string[];
  REMITTANCE_PERMISSIONS_GROUP: string[];
  URGENT_INTERVENTION_PERMISSIONS_GROUP: string[];
  CHARITY_ORG_TEAM: string;
  SEARCH_PERMISSION_GROUP: string[];
  GIVE_USERS_PERMISSIONS: string[];
  BENEFICIARY_AUDIT_LIMIT: number;
  E_SERVICE_ITEM_KEY: string;
  REPORTS_URL: string
}
