export interface ILanguageKeys {
  provide_request: string;
  administration : string;
  inquiries : string;
  custom_role : string;
  users: string;
  organizations: string;
  aid: string;
  delete_x_success: string;
  confirm_delete_x: string;
  no: string;
  yes: string;
  create_x_success: string;
  update_x_success: string;
  specific_min_length: string;
  too_short: string;
  required_field: string;
  add_localization: string;
  actions: string;
  english_name: string;
  arabic_name: string;
  localization_key: string;
  identifier: string;
  localization: string;
  hide_password: string;
  show_password: string;
  login: string;
  lang: string;
  password: string;
  username: string;
  enter_mobile_or_email: string;
  enter_your_password_here: string;
}
