import {Lookup} from '../models/lookup';

export interface ILookupMap {
  ServiceWorkField: Lookup[];
  CommonStatus: Lookup[];
  AidLookupStatus: Lookup[];
  SubRequestStatus: Lookup[];
  BenCategory: Lookup[];
  SubRequestType: Lookup[];
  Countries: Lookup[];
  BenOccuptionStatus: Lookup[];
  AidType: Lookup[];
  Nationality: Lookup[];
  OrgStatus: Lookup[];
  OrgUnitType: Lookup[];
  OrgUserJobTitle: Lookup[];
  OrgUserPermissionGroup: Lookup[];
  OrgUserStatus: Lookup[];
  OrgUserType: Lookup[];
  SubAidPeriodicType: Lookup[];
  BenAddressStatus: Lookup[];
  BenEducationLevel: Lookup[];
  BenIdType: Lookup[];
  BenMaritialStatus: Lookup[];
  Gender: Lookup[];
  GovOccuptionStatus: Lookup[];
  GovOccuptionType: Lookup[];
  ResidenceStatus: Lookup[];
  GulfCountries: Lookup[];
  WORK_FIELD: Lookup[];
  ATTACHMENT_TYPE: Lookup[];
  InquiryCategory: Lookup[];
  ConsultationCategory: Lookup[];
  InquiryStatus: Lookup[];
  ConsultationStatus: Lookup[];
  ServiceRequestType: Lookup[];
  BankCategory: Lookup[];
  Currency: Lookup[];
  Domain: Lookup[];
  HeadQuarterType: Lookup[];
  RequestClassification: Lookup[];
}
