export enum ActionIconsEnum {
  ADD = 'mdi-plus-box',
  ADD_SIMPLE = 'mdi-plus',
  RELOAD = 'mdi-reload',
  EDIT = 'mdi-pen',
  EDIT_BOOK = 'mdi-book-edit',
  EDIT_USER = 'mdi-account-edit',
  CANCEL = 'mdi-close',
  CANCEL_BOOK = 'mdi-book-cancel',
  VIEW = 'mdi-eye',
  DELETE = 'mdi-close-box',
  DELETE_TRASH = 'mdi-delete',
  LOGS = 'mdi-history',
  CHILD_ITEMS = 'mdi-circle-multiple',
  STATUS = 'mdi-list-status',
  PRINT = 'mdi-printer',
  SWITCH_INACTIVE = 'mdi-toggle-switch-off',
  SWITCH_ACTIVE = 'mdi-toggle-switch',
  DETAILS = 'mdi-view-list',
  CURRENCY = 'mdi-currency-rial',
  DOLLAR = 'mdi-currency-usd',
  AID_HELP = 'mdi-handshake',
  SEARCH_USER = 'mdi-account-search',
  DOWNLOAD = 'mdi-download',
  SPECIAL_NEEDS = 'mdi-human',
  CHECKLIST = 'mdi-format-list-bulleted-square'
}
