export enum AdminLookupTypeEnum {
  WORK_FIELD = 0,
  OCHA = 1,
  DAC = 2,
  ACTIVITY_TYPE = 3,
  TEMPLATE_INDICATOR = 4,
  EXIT_MECHANISM = 5,
  BYLAWS_CLASSIFICATION = 6,
  RISK_TYPE = 7,
  RISK_CLASSIFICATION = 8,
  COORDINATION_SUPPORT_CLASSIFICATION = 9,
  RESOLUTIONS_ISSUED = 10,
  PENALTIES_DECISION = 11,
  GENERAL_PROCESS_CLASSIFICATION = 12,
  SERVICE_TYPE = 13,
  FUNCTIONAL_GROUP = 14,
  PERMISSION_GROUP = 15
}
