export enum AdminLookupTypeEnum {
  DAC_OCHA = 1001,
  OCHA = 1,
  DAC = 2,
  RISK_TYPE = 7,
  ACTIVITY_TYPE = 3,
  RESOLUTIONS_ISSUED = 10,
  COORDINATION_SUPPORT_CLASSIFICATION = 9,
  BYLAWS_CLASSIFICATION = 6,
  RISK_CLASSIFICATION = 8,
  INTERNAL_AID_CLASSIFICATION = 5,
  REGISTRATION_ENTITY = 4,
  PENALTIES_DECISION = 11
}
