export enum BeneficiarySaveStatus {
  FAILED = 'FAILED',
  SAVED = 'SAVED',
  EXISTING = 'BENEIFICARY_ALREADY_EXISTING',
  NDA_ACTIVE_REQUESTS_EXISTING = 'BENEIFICARY_NDA_ACTIVE_REQUESTS_EXISTING',
  NDA_RECENT_AID_EXISTING = 'BENEIFICARY_NDA_RECENT_AID_EXISTING',
  NDA_RECENT_PERIODIC_AIDS_EXISTING = 'BENEIFICARY_NDA_RECENT_PERIODIC_AIDS_EXISTING'
}
