export enum CaseTypes {
  INQUIRY = 1,
  CONSULTATION,
  INTERNATIONAL_COOPERATION,
  INITIAL_EXTERNAL_OFFICE_APPROVAL = 6,
  PARTNER_APPROVAL = 7,
  FINAL_EXTERNAL_OFFICE_APPROVAL = 8,
  INTERNAL_PROJECT_LICENSE = 11,
  EXTERNAL_PROJECT_MODELS = 9,
}
