export enum CaseTypes {
  INQUIRY = 1,
  CONSULTATION = 2,
  INTERNATIONAL_COOPERATION = 3,
  INITIAL_EXTERNAL_OFFICE_APPROVAL = 6,
  PARTNER_APPROVAL = 7,
  FINAL_EXTERNAL_OFFICE_APPROVAL = 8,
  INTERNAL_PROJECT_LICENSE = 11,
  EXTERNAL_PROJECT_MODELS = 9,
  URGENT_INTERVENTION_LICENSING = 12,
  EXTERNAL_PROJECT_IMPLEMENTATION = 13,
  COLLECTION_APPROVAL = 14,
  COLLECTOR_LICENSING = 16,
  FUNDRAISING_LICENSING = 17,
  CUSTOMS_EXEMPTION_REMITTANCE = 18,
  INTERNAL_BANK_ACCOUNT_APPROVAL = 21,
  URGENT_JOINT_RELIEF_CAMPAIGN = 22,
  URGENT_INTERVENTION_REPORTING = 20
}
