export enum CommonCaseStatus {
  CANCELLED = 0,
  DRAFT = 1,
  NEW = 2,
  UNDER_PROCESSING = 3,
  INITIAL_APPROVE = 4,
  FINAL_APPROVE = 5,
  RETURNED = 6,
  FINAL_REJECTION = 7,
  FINAL_NOTIFICATION = 8,
  RECEIVED = 9,
  UNDER_EXAMINATION = 11
}
