export enum EServicePermissions {
  // e-service permissions permission name should be same name as CaseType enum
  INQUIRY = 'INQUIRY',
  CONSULTATION = 'CONSULTATION',
  INTERNATIONAL_COOPERATION = 'INTERNATIONAL_COOPERATION',
  INTERNAL_PROJECT_LICENSE = 'INTERNAL_PROJECT_LICENSE',
  EXTERNAL_PROJECT_MODELS = 'EXTERNAL_PROJECT_MODELS',
  INITIAL_EXTERNAL_OFFICE_APPROVAL = 'INITIAL_EXTERNAL_OFFICE_APPROVAL',
  PARTNER_APPROVAL = 'PARTNER_APPROVAL',
  FINAL_EXTERNAL_OFFICE_APPROVAL = 'FINAL_EXTERNAL_OFFICE_APPROVAL',
  URGENT_INTERVENTION_LICENSING = 'URGENT_INTERVENTION_LICENSING',
  COLLECTION_APPROVAL = 'COLLECTION_APPROVAL',
  COLLECTOR_LICENSING = 'COLLECTOR_LICENSING',
  FUNDRAISING_LICENSING = 'FUNDRAISING_LICENSING',
  INTERNAL_BANK_ACCOUNT_APPROVAL = 'INTERNAL_BANK_ACCOUNT_APPROVAL',
  SHIPPING_APPROVAL = 'SHIPPING_APPROVAL',
  E_SERVICES_SEARCH = 'E_SERVICES_SEARCH',
  URGENT_JOINT_RELIEF_CAMPAIGN = ''
}
