export enum EServicePermissions {
  // e-service permissions permission name should be same name as CaseType enum
  INQUIRY = 'INQUIRY',
  CONSULTATION = 'CONSULTATION',
  INTERNATIONAL_COOPERATION = 'INTERNATIONAL_COOPERATION',
  INTERNAL_PROJECT_LICENSE = 'INTERNAL_PROJECT_LICENSE',
  EXTERNAL_PROJECT_MODELS = 'EXTERNAL_PROJECT_MODELS',
  INITIAL_EXTERNAL_OFFICE_APPROVAL = 'INITIAL_EXTERNAL_OFFICE_APPROVAL',
  PARTNER_APPROVAL = 'PARTNER_APPROVAL',
  FINAL_EXTERNAL_OFFICE_APPROVAL = 'FINAL_EXTERNAL_OFFICE_APPROVAL'
}
