export enum FinancialTransferTypes{
  PARTICIPATION_IN_INTERNATIONAL_CONFERENCES = 1,
  PROJECTS_FOR_EXECUTING_AGENCY = 2,
  PROJECTS_TO_OTHERS =3,
  OVERSEAS_OFFICE_OPERATING_EXPENSES =4,
  MEMBERSHIP_IN_INTERNATIONAL_PROFESSIONAL_ASSOCIATIONS =5,
  CONSULTING_SERVICES =6,
  PURCHASES_FROM_OUTSIDE_COUNTRY =7,
  OTHER_TRANSFERS = 9,
}
