export enum GdxServicesEnum {
  MOPH = '1',
  MOCI = '2',
  MOJ = '3',
  MAWARED = '4',
  GARSIA = '5',
  IZZAB = '6',
  KAHRAMAA = '7',
  MOL = '8',
  SJC = '9',
  MOE = '10',
  MME = '11',
  QATAR_CHARITY = '12',
  EID_CHARITABLE_FOUNDATION = '13',
  QATAR_RED_CRESCENT = '14',
  HOUSING_BENEFICIARY_STATUS = '15',
  SECURITY_BENEFICIARY_STATUS = '16',
  QCB = '17',
  MOI_ADDRESS_INFO = '18',
  MOI_PERSONAL_INFO = '19',
}
