export enum GdxServiceRelatedTypesEnum {
  MOJ_FLATS = 'moj_flats',
  MOJ_PARCELS = 'moj_parcels',
  MOCI_COMPANIES = 'moci_companies',
  MAWARED_EMPLOYEES = 'mawared_employees',
  GARSIA_PENSION = 'garsia_pensions',
  GARSIA_PENSION_PAYMENT = 'garsia_pension_payments',
  IZZAB_RELATED = 'izzab_related',
  KAHRAMAA_OUTSTANDING_PAYMENTS = 'kahramaa_outstanding_payments',
  MOL_RELATED_DATA = 'mol_related_data',
  SJC_RELATED_DATA = 'sjc_related_data',
  MOE_STUDENT_INFO = 'moe_student_info',
  MOE_INSTALLMENTS ='moe_installments',
  MOE_PENDING_PAYMENTS = 'moe_pending_payments',
  MME_LEASED_CONTRACT = 'mme_leased_contract',
}
