export enum GeneralAssociationMeetingStepNameEnum {
  SUPERVISION_AND_CONTROL_REVIEW = 'SPEC_REV',
  SUPERVISION_MANAGER_REVIEW = 'MNGR_REV',
  DECISION_MAKER_REVIEW = 'DEC_MAK_REV',
  DECISION_MAKER_REWORK = 'DEC_MAK_REW',
  MEMBER_REVIEW = 'MEMBER_REV',
  MANAGER_FINAL_REVIEW = 'MNGR_FINAL_REV',
  SUPERVISION_AND_CONTROL_REWORK = 'SPEC_REW',
  CharityManagerReview = 'ORG_REV'
}
