export enum Permissions {
  TRAINING_BUNDLE = 'TRAINING_BUNDLE',
  TRAINING_CERTIFICATE_TRAINEE = 'TRAINING_CERTIFICATE_TRAINEE',
  ADD_PUBLISH_TRAINING = 'ADD_PUBLISH_TRAINING',
  TRAINING_MANAGE_TRAINEE = 'TRAINING_MANAGE_TRAINEE',
  TRAINING_ADD_TRAINEE = 'TRAINING_ADD_TRAINEE', // add accredit trainers
  TRAINING_SURVEY_TEMPLATE = 'TRAINING_SURVEY_TEMPLATE',
  TRAINING_SURVEY_EDIT_QUESTION = 'TRAINING_SURVEY_EDIT_QUESTION',
}
