export enum Permissions {
  TRAINING_BUNDLE = 'TRAINING_BUNDLE',
  TRAINING_CERTIFICATE_TRAINEE = 'TRAINING_CERTIFICATE_TRAINEE',
  TRAINING_ADD_PUBLISH_PROGRAM = 'TRAINING_ADD_PUBLISH_PROGRAM',
  TRAINING_MANAGE_TRAINEE = 'TRAINING_MANAGE_TRAINEE',
  TRAINING_ADD_TRAINEE = 'TRAINING_ADD_TRAINEE', // add accredit trainers
  TRAINING_SURVEY_TEMPLATE = 'TRAINING_SURVEY_TEMPLATE',
  TRAINING_SURVEY_EDIT_QUESTION = 'TRAINING_SURVEY_EDIT_QUESTION',
  TRAINING_CERTIFICATE_TEMPLATE = 'TRAINING_CERTIFICATE_TEMPLATE', // used in menu item do not remove
  TRAINING_CHARITY_MANAGEMENT = 'TRAINING_CHARITY_MANAGEMENT', // used in menu item do not remove
  DONOR_MANAGEMENT = 'DONOR_MANAGEMENT',
  INQUIRY_LOGS = ''
}

/*
* TRAINING_BUNDLE
* MANAGE_CERTIFICATE_TEMPLATES
*
* */
