export enum PermissionGroup {
  E_SERVICES_PERMISSIONS_GROUP = 'E_SERVICES_PERMISSIONS_GROUP',
  PROJECTS_PERMISSION_GROUP = 'PROJECTS_PERMISSION_GROUP',
  ADMIN_PERMISSIONS_GROUP = 'ADMIN_PERMISSIONS_GROUP',
  TRAINING_PROGRAMS_PAGE_GROUP = 'TRAINING_PROGRAMS_PAGE_GROUP',
  TRAINING_PROGRAMS_MENU_ITEM_GROUP = 'TRAINING_PROGRAMS_MENU_ITEM_GROUP',
  COLLECTION_SERVICES_GROUP = 'COLLECTION_SERVICES_GROUP'
}
