export enum ProfileTypes {
  CHARITY = 1,
  NPO,
  INSTITUTION,
  GOVERMENT_AGENCIES,
  REGISTERED_ENTITES,
  INDIVIDUALS_FOR_THE_PURPOSE_OF_COLLECTING_DONATIONS,
  INTERNATIONAL_COOPERATION_BODIES,
  INTERNATIONAL_ORGANIZATIONS,
  COMPANIES,
  COMMUNITIES,
  OTHER
}
