export enum ProfileTypes {
  CHARITY = 1,
  NON_PROFIT_ORGANIZATIONS = 2,
  INSTITUTION = 3,
  GOVERNMENT_AGENCIES = 4,
  REGISTERED_ENTITIES = 5,
  ORGANIZATIONS_FOR_PURPOSE_OF_DONATIONS = 6,
  INTERNATIONAL_COOPERATION_BODIES = 7,
  INTERNATIONAL_ORGANIZATIONS = 8,
  COMPANIES = 9,
  COMMUNITIES = 10,
  OTHER = 11,
}
