export enum ServiceActionType {
  To_Manager = 12,
  Competent_Department = 5,
  To_General_Manager = 21,
  To_Construction_Expert = 23,
  to_Devlopmental_Expert = 22,
  To_User = 7,
  Postpone = 16,
  Sent = 13,
  Created = 1,
  Canceled = 9,
  Updated = 3,
  Rejected = 10,
  Approved = 8,
  Claimed = 2,
  Returned = 6,
  Viewed = 11,
  complete = 4,
  Partner_Approval_Review = 14,
  Supervision_and_Control_Review = 24,
  Review_Initial_External_Office = 17,
  Review_Final_External_Office = 18,
  Draft = 20,
  Final_Approve = 15,
  Approve_And_Fill = 19,
}
