export enum SystemMenuKeys {
  ADMINISTRATION = 'ADMINISTRATION',
  GENERAL_SERVICES = 'GENERAL_SERVICES',
  SANADY = 'SANADY',
  PROJECTS_SERVICES = 'PROJECTS_SERVICES',
  TRAINING_SERVICES = 'TRAINING_SERVICES',
  COLLECTION_SERVICES = 'COLLECTION_SERVICES',
  REMITTANCE_SERVICES = 'REMITTANCE_SERVICES',
  OFFICE_SERVICES = 'OFFICE_SERVICES',
  URGENT_INTERVENTION_SERVICES = 'URGENT_INTERVENTION_SERVICES'
}
