export enum TaskState {
  STATE_CLAIMED = 'STATE_CLAIMED',
  STATE_FINISHED = 'STATE_FINISHED',
  STATE_INACTIVE = 'STATE_INACTIVE',
  STATE_RUNNING = 'STATE_RUNNING',
  STATE_SUSPENDED_BY_PARENT = 'STATE_SUSPENDED_BY_PARENT',
  STATE_TERMINATED = 'STATE_TERMINATED',
  STATE_READY = 'STATE_READY'
}
