export enum TrainingStatus {
  DATA_ENTERED = 1,
  PROGRAM_APPROVED = 2,
  REGISTRATION_OPEN = 3,
  REGISTRATION_CLOSED = 4,
  TRAINING_FINISHED = 5,
  TRAINING_CANCELED = 6,
  TRAINING_PUBLISHED = 7,
  EDITING_AFTER_PUBLISHING = 8,
  DATA_UPDATED = 9
}
